services:
  - type: web
    name: bruno-license-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BRUNO_LICENSE_PLAN
        value: ULTIMATE_EDITION
      - key: BRUNO_LICENSE_TYPE
        value: personal
